# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlEks < Formula
  desc ""
  homepage "https://github.com/surajincloud/homebrew-tools"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.1/kubectl-eks_0.4.1_darwin_amd64.tar.gz"
      sha256 "5cf32fe238b726436093de670f55633f6ce1b4fbae4fda450a86f51b397b365e"

      def install
        bin.install "kubectl-eks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.1/kubectl-eks_0.4.1_darwin_arm64.tar.gz"
      sha256 "11ab86578940fd08c02810e0505698f2e6b6ac309e32fbb6e7a9ae534dfe2181"

      def install
        bin.install "kubectl-eks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.1/kubectl-eks_0.4.1_linux_arm64.tar.gz"
      sha256 "5643dc931e6f4b05e5c3c461775276d376468522e3fc546db73b85df8f2f8065"

      def install
        bin.install "kubectl-eks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.1/kubectl-eks_0.4.1_linux_amd64.tar.gz"
      sha256 "ac550720a5d2015f1aea056b295979f954a83e1c2706d0c5c06be5456995e030"

      def install
        bin.install "kubectl-eks"
      end
    end
  end
end
