# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlEks < Formula
  desc ""
  homepage "https://github.com/surajincloud/homebrew-tools"
  version "0.4.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.4/kubectl-eks_0.4.4_darwin_amd64.tar.gz"
      sha256 "1d695e82fc5fd0a5dd883e5ee461cc1a8188c094640523adb9c88d505e82e362"

      def install
        bin.install "kubectl-eks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.4/kubectl-eks_0.4.4_darwin_arm64.tar.gz"
      sha256 "2c9b222b8847782da915fce524c542dd22db648246168808203d178e83a5c450"

      def install
        bin.install "kubectl-eks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.4/kubectl-eks_0.4.4_linux_arm64.tar.gz"
      sha256 "02edf2344605085d5ac4fb1db8636aa77c73866234a1e1337eecfdc806b2800a"

      def install
        bin.install "kubectl-eks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/surajincloud/kubectl-eks/releases/download/v0.4.4/kubectl-eks_0.4.4_linux_amd64.tar.gz"
      sha256 "eb5811e3ce013136cb3fea3eec010ce65e0f716d3327045c3561f155a95187c8"

      def install
        bin.install "kubectl-eks"
      end
    end
  end
end
